import i18next from 'i18next';
import { authRoles } from 'bpw-auth/model';
import en from './navigation-i18n/en';
import fr from './navigation-i18n/fr';

i18next.addResourceBundle('en', 'navigation', en, true);
i18next.addResourceBundle('fr', 'navigation', fr, true);
const navigationConfig = [
  {
    id: 'authentication',
    title: 'Authentication',
    translate: 'Authentication',
    translate: 'NAV.AUTH.AUTHTICATION.TITLE',
    type: 'group', // 'collapse',
    icon: 'lock',
    badge: {
      title: 10,
      bg: '#525E8A',
      fg: '#FFFFFF',
    },
    children: [
      {
        id: 'login',
        title: 'Login',
        type: 'item',
        url: '/auth/login',
        translate: 'NAV.AUTH.LOGIN.TITLE',
        auth: authRoles.onlyGuest,
        icon: 'lock',
      },
      {
        id: 'logout',
        title: 'Logout',
        type: 'item',
        auth: authRoles.user,
        translate: 'NAV.AUTH.LOGOUT.TITLE',
        url: '/auth/logout',
        icon: 'exit_to_app',
      },
      {
        id: 'register',
        title: 'Register',
        type: 'item',
        url: '/auth/register',
        translate: 'NAV.AUTH.REGISTER.TITLE',
        auth: authRoles.onlyGuest,
        icon: 'person_add',
      },
      {
        id: 'authentication-forgot-password',
        title: 'Forgot Password',
        type: 'item',
        auth: authRoles.onlyGuest,
        translate: 'NAV.AUTH.FORGOT_PASSWORD.TITLE',
        url: '/auth/forgot-password',
      },
      {
        id: 'authentication-reset-password',
        title: 'Reset Password',
        type: 'item',
        translate: 'NAV.AUTH.RESET_PASSWORD.TITLE',
        url: '/auth/reset-password',
      },
      {
        id: 'authentication-lock-screen',
        title: 'Lock Screen',
        type: 'item',
        translate: 'NAV.AUTH.LOCK_SCREEN.TITLE',
        url: '/auth/lock',
      },
      {
        id: 'authentication-mail-confirmation',
        title: 'Mail Confirmation',
        type: 'item',
        translate: 'NAV.AUTH.MAIL_CONFIRM.TITLE',
        url: '/auth/mail-confirm',
      },
    ],
  },
  // {
  //   id: 'apigateway_home',
  //   title: 'api_gateway_home',
  //   translate: 'NAV.API.HOME.TITLE',
  //   type: 'item',
  //   icon: 'app',
  //   url: '/apigateway/home',
  // },
  // {
  //   id: 'apigateway_handlers',
  //   title: 'api_gateway_handlers',
  //   translate: 'NAV.API.HANDLERS.TITLE',
  //   type: 'group',
  //   icon: 'apps',
  //   children: [
  //     {
  //       id: 'apigateway_handlers_firewall',
  //       title: 'api_gateway_handlers_firewall',
  //       translate: 'NAV.API.HANDLERS_FIREWALL.TITLE',
  //       type: 'item',
  //       icon: 'whatshot',
  //       url: '/apigateway/handlers/firewall',
  //     },
  //     {
  //       id: 'apigateway_handlers_sign',
  //       title: 'api_gateway_handlers_sign',
  //       translate: 'NAV.API.HANDLERS_SIGN.TITLE',
  //       type: 'item',
  //       icon: 'whatshot',
  //       url: '/apigateway/handlers/sign',
  //     },
  //     {
  //       id: 'apigateway_handlers_monitor',
  //       title: 'api_gateway_handlers_monitor',
  //       translate: 'NAV.API.HANDLERS_MONITOR.TITLE',
  //       type: 'item',
  //       icon: 'whatshot',
  //       url: '/apigateway/handlers/monitor',
  //     },
  //     {
  //       id: 'apigateway_handlers_rewrite',
  //       title: 'api_gateway_handlers_rewrite',
  //       translate: 'NAV.API.HANDLERS_REWRITE.TITLE',
  //       type: 'item',
  //       icon: 'whatshot',
  //       url: '/apigateway/handlers/rewrite',
  //     },
  //     {
  //       id: 'apigateway_handlers_rate_limiter',
  //       title: 'api_gateway_handlers_rate_limiter',
  //       translate: 'NAV.API.HANDLERS_RATE_LIMITER.TITLE',
  //       type: 'item',
  //       icon: 'whatshot',
  //       url: '/apigateway/handlers/rate_limiter',
  //     },
  //     {
  //       id: 'apigateway_handlers_divide',
  //       title: 'api_gateway_handlers_divide',
  //       translate: 'NAV.API.HANDLERS_DIVIDE.TITLE',
  //       type: 'item',
  //       icon: 'whatshot',
  //       url: '/apigateway/handlers/divide',
  //     },
  //     {
  //       id: 'apigateway_handlers_springCloud',
  //       title: 'api_gateway_handlers_springCloud',
  //       translate: 'NAV.API.HANDLERS_SPRING_CLOUD.TITLE',
  //       type: 'item',
  //       icon: 'whatshot',
  //       url: '/apigateway/handlers/springCloud',
  //     },
  //     {
  //       id: 'apigateway_handlers_hystrix',
  //       title: 'api_gateway_handlers_hystrix',
  //       translate: 'NAV.API.HANDLERS_HYSTRIX.TITLE',
  //       type: 'item',
  //       icon: 'whatshot',
  //       url: '/apigateway/handlers/hystrix',
  //     },
  //   ],
  // },
  // {
  //   id: 'api-gateway_system',
  //   title: 'api_gateway_system',
  //   translate: 'NAV.API.SYSTEM.TITLE',
  //   type: 'group',
  //   icon: 'apps',
  //   children: [
  //     {
  //       id: 'apigateway_system_metadata',
  //       title: 'api_gateway_system_metadata',
  //       translate: 'NAV.API.SYSTEM_METADATA.TITLE',
  //       type: 'item',
  //       icon: 'whatshot',
  //       url: '/apigateway/system/metadata',
  //     },
  //     {
  //       id: 'apigateway_system_handlers',
  //       title: 'api_gateway_system_handlers',
  //       translate: 'NAV.API.SYSTEM_HANDLERS.TITLE',
  //       type: 'item',
  //       icon: 'whatshot',
  //       url: '/apigateway/system/handlers',
  //     },
  //     {
  //       id: 'apigateway_system_certificate',
  //       title: 'api_gateway_system_certificate',
  //       translate: 'NAV.API.SYSTEM_CERTIFICATE.TITLE',
  //       type: 'item',
  //       icon: 'whatshot',
  //       url: '/apigateway/system/certificate',
  //     },
  //     {
  //       id: 'apigateway_system_account',
  //       title: 'api_gateway_system_account',
  //       translate: 'NAV.API.SYSTEM_ACCOUNT.TITLE',
  //       type: 'item',
  //       icon: 'whatshot',
  //       url: '/apigateway/system/account',
  //     },
  //   ],
  // },
  // {
  //   id: 'authorization',
  //   title: 'Authorization',
  //   type: 'group',
  //   icon: 'apps',
  //   translate: 'NAV.AUTHORIZATION.TITLE',
  //   children: [
  //     {
  //       id: 'auth-admin-example',
  //       title: 'Admin: Auth protected page',
  //       translate: 'NAV.AUTHORIZATION.PROTECTED_PAGE_ADMIN.TITLE',
  //       type: 'item',
  //       url: '/pages/authorization/admin-role-example',
  //       icon: 'security',
  //       auth: authRoles.admin,
  //     },
  //     {
  //       id: 'only-admin-navigation-item',
  //       title: 'Nav item only for Admin',
  //       translate: 'NAV.AUTHORIZATION.NAV_ITEM_ONLY_ADMIN.TITLE',
  //       type: 'item',
  //       url: '/pages/authorization/admin-role-example',
  //       icon: 'verified_user',
  //       auth: authRoles.admin,
  //     },
  //     {
  //       id: 'auth-user-example',
  //       title: 'User: Auth protected page',
  //       translate: 'NAV.AUTHORIZATION.PROTECTED_PAGE_USER.TITLE',
  //       type: 'item',
  //       url: '/pages/authorization/user-role-example',
  //       icon: 'security',
  //       auth: authRoles.user,
  //     },
  //     {
  //       id: 'only-user-navigation-item',
  //       title: 'Nav item only for User',
  //       translate: 'NAV.AUTHORIZATION.NAV_ITEM_ONLY_USER.TITLE',
  //       type: 'item',
  //       url: '/pages/authorization/user-role-example',
  //       icon: 'verified_user',
  //       auth: authRoles.user,
  //     },
  //     {
  //       id: 'auth-guest-example',
  //       title: 'Guest: Auth protected page',
  //       type: 'item',
  //       translate: 'NAV.AUTHORIZATION.PROTECTED_PAGE_STAFF_GUEST.TITLE',
  //       url: '/pages/authorization/guest-role-example',
  //       icon: 'security',
  //       auth: authRoles.onlyGuest,
  //     },
  //     {
  //       id: 'only-guest-navigation-item',
  //       title: 'Nav item only for Guest',
  //       type: 'item',
  //       translate: 'NAV.AUTHORIZATION.NAV_ITEM_ONLY_GUEST.TITLE',
  //       url: '/pages/authorization/guest-role-example',
  //       icon: 'verified_user',
  //       auth: authRoles.onlyGuest,
  //     },
  //  ],
  // },
];

export default navigationConfig;
